@extends('layouts.template')
@section('menu')
@include('layouts.menu')
@endsection
@section('header')
@include('layouts.header')
@endsection
@section('habilidades')
@include('layouts.habilidades')
@endsection
@section('portafolio')
@include('layouts.portafolio')
@endsection
@section('contacto')
@include('layouts.contacto')
@endsection
@section('footer')
@include('layouts.footer')
@endsection